name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./MusicTonic
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      # run: mvn -B package --file pom.xml 
      run: mvn -B package --file pom.xml -Dmaven.test.skip=true
    - name: Run Codacy Analysis CLI
      uses: codacy/codacy-analysis-cli-action@master
      with:
        tool: SpotBugs
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        upload: true
        max-allowed-issues: 2147483647
    - name: Test with Maven
      run: mvn -X test --file pom.xml
    - name: Show the report for JaCoCo
      uses: actions/upload-artifact@v3
      with:
        name: report
        path: /home/runner/work/friendly-couscous/friendly-couscous/MusicTonic/target/site/jacoco/jacoco.csv
    - name: Download the report
      uses: actions/download-artifact@v3
    - name: Setup .NET Core # Required to execute ReportGenerator
      uses: actions/setup-dotnet@v3
      with:
       dotnet-version: 6.x
       dotnet-quality: 'ga'
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: /home/runner/work/friendly-couscous/friendly-couscous/MusicTonic/target/site/jacoco/jacoco.xml
    - name: Generate additional JaCoCo reports
      uses: danielpalme/ReportGenerator-GitHub-Action@5.1.12
      with:
        reports: /home/runner/work/friendly-couscous/friendly-couscous/MusicTonic/target/site/jacoco/jacoco.xml
        targetdir: /home/runner/work/friendly-couscous/friendly-couscous/MusicTonic/target/site/jacoco
        reporttypes: MarkdownSummary;PngChart;Badges
    - name: Push JaCoCo to repository 
      run: |
       git config --global user.name "J-Rebs"
       git config --global user.email "jr4162@columbia.edu"

       git add -f /home/runner/work/friendly-couscous/friendly-couscous/MusicTonic/target/site/jacoco; git commit -m "JaCoCo reports"
       git push
#    - name: Client1 Controller Test
#      run: mvn -X -Dtest=Client1ControllerTest test
#    - name: Client2 Controller Test
#      run: mvn -Dtest=Client2ControllerTest test
#    - name: Client3 Controller Test
#      run: mvn -Dtest=Client3ControllerTest test
#    - name: Client1 Service Test
#      run: mvn -Dtest=Client1ServiceTest test
#    - name: Client2 Service Test
#      run: mvn -Dtest=Client2ServiceTest test
#    - name: Integration Test
#      run: mvn -X -Dtest=IntegrationTest test
#    - name: Full Tests with JaCoCo
#      run: mvn test -f pom.xml

